import Head from "next/head";
import { Button } from "~/components/ui/button";
import { Moon, Sun } from "lucide-react"
import { api } from "~/utils/api";
import { useTheme } from "next-themes"

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const { setTheme } = useTheme()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen items-center justify-center gap-8">
        <h1>Hello World</h1>
        <Button>
          Pencet
        </Button>
        <Button onClick={() => setTheme("dark")} size="icon">
          <Moon />
        </Button>
        <Button onClick={() => setTheme("light")} size="icon">
          <Sun />
        </Button>
      </main>
    </>
  );
}
